services:
  api:
    image: datascientest/fastapi:1.0.0
    container_name: api
    ports:
      - "8000:8000"
    networks:
      - my_network

  authentication_test:
    build:
      context: .
      dockerfile: Dockerfile
    image: authentication_test_container:latest
    container_name: authentication_test
    environment:
      - API_ADDRESS=api
      - API_PORT=8000
      - LOG=1
    networks:
      - my_network
    volumes:
      - ./Docker_exam/logs:/authentication_test/logs
    depends_on:
      - api

networks:
  my_network:
    driver: bridge