# image for Content
FROM python:3.11-slim

RUN pip install requests

COPY content_test.py /content_test/content_test.py

WORKDIR /content_test/

CMD ["python", "content_test.py"]

LABEL test_type="content_test"